#!/shared/utils.x86_64/python-2.7/bin/python
"""
Created on Thu Oct 29 10:08:50 2015

@author: mattv
"""

import os
import time
import sys
import stat
from cats_mapping.hemodynamics.hemo_demix import demix


if __name__ == "__main__":           

	paths = [r"/allen/programs/braintv/workgroups/nc-ophys/CorticalMapping/IntrinsicImageData/170518-M287480/170518_M287480_alldat"] 
   
	id_tag = time.strftime("%Y%m%d-%H%M%S") # timestamp identifies the job

	def run_jobs(datpath, k, id_tag):     

		paths_470 = np.arange(.1, 1.5, .1)
		paths_530 = np.arange(.1, 1.1, .1)
		paths_590 = np.arange(.1, 1.5, .1)   
	    
	    for p,path_470 in enumerate(paths_470):
	        for pp,path_530 in enumerate(paths_530):
	            for ppp,path_590 in enumerate(paths_590):  

	                params = [path_470, path_530, path_590]

	                savepath = r'/allen/programs/braintv/workgroups/nc-ophys/Matt/corrdata/batch_out'
	                savepath_id = os.path.join(savepath, id_tag)
	                if os.path.isdir(savepath_id) == False:
            			os.mkdir(savepath_id)

	                path_str = str(path_470) + '_' + str(path_530) + '_' + str(path_640)
	                base_fname = 'paths_'  + path_str + '_' + str(id_tag)
	                base_fpath = os.path.join(savepath_id, base_fname)

	                shell_save_path = r'/data/nc-ophys/Matt/batch_scripts'
			        shell_fname = base_fname + '.py'
			        shell_fpath = os.path.join(shell_save_path, shell_fname)

			        datsavepath

	                file = open(shell_fpath, 'w+') 
	                file.writelines( ['import sys\n' ,
	                                  'sys.path.append(r\'/data/nc-ophys/Matt/\')\n' ,
	                                  'from cats_mapping.hemodynamics.hemo_demix import demix\n', 
	                                  'demix(\'' + datpath + '\', \'' + params + '\', \'' + datsavepath + '\')',                 
	                                  ] )
	                file.close()  
	                time.sleep(.5)
	                
	                jobname = 'hemo_demix_batch_%d' % k
	                file = open(jobname + '.sub', 'w+')
	                file.writelines( [ '#!/bin/sh\n',
	                                   '#PBS -N %s\n' % jobname ,
	                                   '#PBS -o %s\n' % (base_fpath + '.out') ,
	                                   '#PBS -q mindscope\n' ,
	                                   '#PBS -j oe\n' ,
	                                   '#PBS -l nodes=1:ppn=1\n' ,
	                                   '#PBS -l walltime=1:00:00\n' ,
	                                   '#PBS -l vmem=8g\n' ,
	                                   '#PBS -m a\n' ,
	                                   '#PBS -r n\n' ,
	                                   'cd $PBS_O_WORKDIR\n' ,
	                                   '\n' ,
	                                   '/shared/utils.x86_64/python-2.7/bin/python ' + shell_fpath + ' > %s\n' % (base_fpath + '.txt')
	                                   ] ) 
	                file.close()
	            
	                os.system('qsub %s' % (jobname + '.sub')) 
	            
	                time.sleep(.5)

	    time.sleep(1.0)

	[run_jobs(datpath, k, id_tag) for k,datpath in enumerate(paths)]    